#!/usr/bin/env bash
# otel-headers.sh — outputs JSON auth headers for Claude Code's otelHeadersHelper
# Generated by setup-apollotech-otel-for-claude.sh. Reads credentials from ~/.claude/apollotech-config.
set -euo pipefail

CONFIG_FILE="${HOME}/.claude/apollotech-config"
APOLLO_USER=""
APOLLO_OTEL_TOKEN=""

if [[ ! -f "${CONFIG_FILE}" ]]; then
    echo "apollotech-otel-headers.sh: config not found at ${CONFIG_FILE}" >&2
    exit 1
fi

while IFS='=' read -r key value; do
    [[ "${key}" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${key// }" ]] && continue
    key="${key#"${key%%[![:space:]]*}"}"
    key="${key%"${key##*[![:space:]]}"}"
    [[ "${key}" != APOLLO_* ]] && continue
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    case "${key}" in
        APOLLO_USER)       APOLLO_USER="${value}" ;;
        APOLLO_OTEL_TOKEN) APOLLO_OTEL_TOKEN="${value}" ;;
    esac
done < "${CONFIG_FILE}"

if [[ -z "${APOLLO_USER}" ]] || [[ -z "${APOLLO_OTEL_TOKEN}" ]]; then
    echo "apollotech-otel-headers.sh: APOLLO_USER or APOLLO_OTEL_TOKEN not set in ${CONFIG_FILE}" >&2
    exit 1
fi

_basic="$(printf '%s:%s' "${APOLLO_USER}" "${APOLLO_OTEL_TOKEN}" | base64 -w0 2>/dev/null || printf '%s:%s' "${APOLLO_USER}" "${APOLLO_OTEL_TOKEN}" | base64 | tr -d '\n')"

# --- Repo detection (best-effort, never fails the script) ---
_repo=""
if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree &>/dev/null; then
    _remote_url="$(git remote get-url origin 2>/dev/null || true)"
    if [[ -n "${_remote_url}" ]]; then
        _repo="$(echo "${_remote_url}" | sed -E 's|.*[:/]([^/]+/[^/]+)$|\1|; s|\.git$||')"
    fi
    if [[ -z "${_repo}" ]]; then
        _git_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
        _repo="$(basename "${_git_root:-${PWD}}")"
    fi
else
    _repo="$(basename "${PWD}")"
fi

_repo="$(printf '%s' "${_repo}" | tr -cd 'a-zA-Z0-9._/-')"

if [[ -n "${_repo}" ]]; then
    printf '{"Authorization": "Basic %s", "X-Apollo-Repository": "%s"}\n' "${_basic}" "${_repo}"
else
    printf '{"Authorization": "Basic %s"}\n' "${_basic}"
fi